Informs the user if they use an invalid verb

diff --git a/src/bin/git-gossip b/src/bin/git-gossip
--- a/src/bin/git-gossip
+++ b/src/bin/git-gossip
@@ -42,6 +42,8 @@ main() {
 		'smudge')
 			smudge "$@"
 			;;
+		*)
+			error "The command '$verb' is invalid"
 	esac
 }
 
@@ -175,6 +177,11 @@ smudgeJsonFile() {
 
 rawKeyToConfigKey() {
 	sed -E 's/[^A-Za-z-]+/-/g'
+}
+
+error() {
+	echo >&2 "$@";
+	exit 1;
 }
 
 debug() {
